spring.application.name=ms-barriodigital-audit

server.port=8084

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.kafka.consumer.group-id=audit-service
spring.kafka.consumer.auto-offset-reset=earliest

# Deserialization & Error Handling
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=cl.duoc.barriodigital.audit.dto.RequestEventDTO
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-shy-glade-acs6skul-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_Pmh8aYoxHne3}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect